version: '3'
services:
  api:
    image: 188252181461.dkr.ecr.us-west-1.amazonaws.com/flexor-instant-quote-admin:api
    env_file:
      - ./api/.env
    ports:
      - '5000:5000'
  ui:
    image: 188252181461.dkr.ecr.us-west-1.amazonaws.com/flexor-instant-quote-admin:ui
    env_file:
      - ./ui/.env
    ports:
      - '80:80'
    depends_on:
      - 'api'